from MADBuf.SubjectGraph import *

def write_blif_to_string(g: BLIFGraph) -> str:

    """
    write the blif to a string
    """

    blif_string = "# Generated by MADBuf\n"

    if g.top_module is None or g.top_module == "":
        g.top_module = "unknown"

    blif_string += ".model " + g.top_module + "\n"

    blif_string += ".inputs "

    for input in g.inputs:
        blif_string += input + " "

    blif_string += "\n"

    blif_string += ".outputs "

    for output in g.outputs:
        blif_string += output + " "

    blif_string += "\n"

    for ro in g.ro_to_ri:
        blif_string += ".latch\t" + g.ro_to_ri[ro] + " " + ro + " 2\n"

    for node in g.const0:
        blif_string += ".names\t" + node + "\n0\n"

    for node in g.const1:
        blif_string += ".names\t" + node + "\n1\n"

    for node in g.nodes:
        blif_string += ".names\t"

        for fanin in g.node_fanins[node]:
            blif_string += fanin + " "

        blif_string += node + "\n"

        for truth_table in g.node_funcs[node]:
            blif_string += truth_table + "\n"

    blif_string += ".end\n"

    return blif_string


def write_blif_to_file(g: BLIFGraph, filename: str):

    """
    write the blif to a file
        TODO:
            - consider also the blackboxes
    """

    f = open(filename, "w")

    f.write(write_blif_to_string(g))

    f.close()
